//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW_ProfileBook.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HW_ProfileBook.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        internal static string Add_Profile {
            get {
                return ResourceManager.GetString("Add Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string Dark_theme {
            get {
                return ResourceManager.GetString("Dark theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password!.
        /// </summary>
        internal static string Invalid_login_or_password_ {
            get {
                return ResourceManager.GetString("Invalid login or password!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must be at least 4 and no more than 16 characters..
        /// </summary>
        internal static string Login_must_be_at_least_4_and_no_more_than_16_characters_ {
            get {
                return ResourceManager.GetString("Login must be at least 4 and no more than 16 characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login should not start with numbers..
        /// </summary>
        internal static string Login_should_not_start_with_numbers_ {
            get {
                return ResourceManager.GetString("Login should not start with numbers.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main List.
        /// </summary>
        internal static string Main_List {
            get {
                return ResourceManager.GetString("Main List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name.
        /// </summary>
        internal static string Nick_name {
            get {
                return ResourceManager.GetString("Nick name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter, one lowercase letter and one number..
        /// </summary>
        internal static string Password_must_contain_at_least_one_uppercase_letter__one_lowercase_letter_and_one_number_ {
            get {
                return ResourceManager.GetString("Password must contain at least one uppercase letter, one lowercase letter and one" +
                        " number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick at gelarry.
        /// </summary>
        internal static string Pick_at_gelarry {
            get {
                return ResourceManager.GetString("Pick at gelarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Sort_by {
            get {
                return ResourceManager.GetString("Sort by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo with camera.
        /// </summary>
        internal static string Take_photo_with_camera {
            get {
                return ResourceManager.GetString("Take photo with camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values in the password and confirm password fields must match..
        /// </summary>
        internal static string The_values_in_the_password_and_confirm_password_fields_must_match_ {
            get {
                return ResourceManager.GetString("The values in the password and confirm password fields must match.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login already taken..
        /// </summary>
        internal static string This_login_already_taken_ {
            get {
                return ResourceManager.GetString("This login already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SignUp.
        /// </summary>
        internal static string User_SignUp {
            get {
                return ResourceManager.GetString("User SignUp", resourceCulture);
            }
        }
    }
}
